services:
  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: conectaqr
      POSTGRES_PASSWORD: 8tNv5J6A7g5UplF0omFn
      POSTGRES_DB: rootDatabase
    ports:
      - "5432:5432"
    command: postgres -c log_min_messages=warning

  server:
    build:
      context: ./Server
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: production
      databaseUrl: postgres://conectaqr:8tNv5J6A7g5UplF0omFn@database:5432/rootDatabase
      JWT_KEY: 8tNv5J6A7g5UplF0omFn
      PUBLIC_DOMAIN: "http://localhost:4000"
      PORT: "4000"

volumes:
  pgdata:
