# Stage de build
FROM node:22-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

ENV NODE_ENV=production
ENV NEXT_PUBLIC_DOMAIN=http://localhost:3000
ENV NEXT_PUBLIC_API_URL=http://localhost:4000
ENV IMAGE_PROTOCOL=http
ENV IMAGE_HOSTNAME=localhost

RUN npm run build

# Stage de produção
FROM node:22-alpine AS runner
WORKDIR /app

COPY --from=builder /app/package*.json ./
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/next.config.ts ./
COPY --from=builder /app/.env ./


RUN npm install --frozen-lockfile --omit=dev
EXPOSE 3000
CMD ["npm", "start"]
